# Generated by Django 4.0.5 on 2022-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter_fname', models.CharField(blank=True, max_length=250)),
                ('setter_lname', models.CharField(blank=True, max_length=250)),
                ('setter_email', models.EmailField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('order_total', models.FloatField()),
                ('is_memoed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='memo',
            name='setter_name',
        ),
    ]
