# Generated by Django 4.0.5 on 2022-07-14 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thetracker', '0002_order_remove_memo_setter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creator_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
